language: java
install: true

jdk:
#  - openjdk11
  - openjdk14

addons:
  sonarcloud:
    organization: "arnosthavelka-github"
      
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dsonar.projectKey=arnosthavelka_security-poc

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
